-- AlterEnum
ALTER TYPE "Localidad" ADD VALUE IF NOT EXISTS 'GBA_ZONA_NORTE';
ALTER TYPE "Localidad" ADD VALUE IF NOT EXISTS 'GBA_ZONA_SUR';
ALTER TYPE "Localidad" ADD VALUE IF NOT EXISTS 'GBA_ZONA_ESTE';
ALTER TYPE "Localidad" ADD VALUE IF NOT EXISTS 'GBA_ZONA_OESTE';
